"""create dailies table

Revision ID: 27d7b093c012
Revises: 7bc612a21204
Create Date: 2023-08-28 21:01:48.988044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d7b093c012'
down_revision = '7bc612a21204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repeats_frame', sa.Enum('daily', 'weekly', 'monthy', 'yearly', name='repeatoptions'), nullable=False),
    sa.Column('repeats_frequency', sa.Integer(), nullable=False),
    sa.Column('repeats_on', sa.Enum('su', 'mo', 'tu', 'we', 'th', 'fr', 'sa', name='daysofweek'), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailies')
    # ### end Alembic commands ###
