"""empty message

Revision ID: a851bbb362c8
Revises: 9b3ea6dc9424
Create Date: 2023-08-29 16:37:53.826474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a851bbb362c8'
down_revision = '9b3ea6dc9424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
