"""create users table

Revision ID: 4672152826f8
Revises:
Create Date: 2023-08-28 20:56:13.381334

"""
from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy.sql import functions

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '4672152826f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('last_login', sa.DateTime, default=functions.now()),
    sa.Column('avatar_url', sa.String(length=255), default='https://res.cloudinary.com/dzntryr5a/image/upload/v1693505136/default-profile-pic_sw5ech.jpg'),
    sa.Column('about', sa.String(length=255)),
    sa.Column('joined', sa.DateTime, default=functions.now()),
    sa.Column('check_ins', sa.Integer, default=1),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
