"""empty message

Revision ID: 14aaa4794c26
Revises: 930145f17936
Create Date: 2023-10-18 18:04:54.033192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14aaa4794c26'
down_revision = '930145f17936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dailies', schema=None) as batch_op:
        batch_op.alter_column('repeats_on',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'),
               existing_nullable=True)

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('dailies', schema=None) as batch_op:
        batch_op.alter_column('repeats_on',
               existing_type=sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###